/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sequencing;

import java.awt.ActiveEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.*;
import static javax.swing.GroupLayout.Alignment.CENTER;

/**
 *
 * @author Mukul Dani
 */
public class Twojobs extends javax.swing.JFrame {

    /**
     * Creates new form Twojobs
     */
    public int num;
    
        JTextField[] mach1 = new JTextField[num];
        JTextField[] mach2 = new JTextField[num];
        ArrayList<Integer> arraymach1 = new ArrayList<Integer>();
        ArrayList<Integer> arraymach2 = new ArrayList<Integer>();
    public Twojobs() {
        num = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtjobno = new javax.swing.JTextField();
        btngo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("addjobstwoMach"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sequencing");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("n Jobs with 2 machines");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Enter the number of Jobs");

        txtjobno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtjobno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtjobno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjobnoActionPerformed(evt);
            }
        });
        txtjobno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtjobnoPropertyChange(evt);
            }
        });

        btngo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btngo.setText("GO");
        btngo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btngoMousePressed(evt);
            }
        });
        btngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(115, 115, 115))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtjobno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btngo)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtjobno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngo))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void goToTwoMachSeq(){
        if(! arraymach1.isEmpty() && !arraymach2.isEmpty()){
            TwoMachSeq tsq = new TwoMachSeq(arraymach1, arraymach2);
            tsq.setVisible(true);
            this.dispose();
        }else{
            //do something
        }
    }
    
    public void getArrays(){
        for(int i=0; i<num; i++){
            String s = mach1[i].getText();
            int t1 = Integer.parseInt(s);
            arraymach1.add(t1);
        }
        for(int i=0; i<num; i++){
            String s1 = mach2[i].getText();
            int t2 = Integer.parseInt(s1);
            arraymach2.add(t2); 
        }
    }
    
    public void setnojobs(){
        System.out.println("Set Jlabel");
        String j = txtjobno.getText();
        num = Integer.parseInt(j);
        mach1 = new JTextField[num];
        mach2 = new JTextField[num];
        JLabel[] jname = new JLabel[num];
        
        JLabel txtm1 = new JLabel();
        txtm1.setText("Machine 1");
        txtm1.setBounds(190, 145, 75, 30);
        txtm1.setVisible(true);
        txtm1.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        txtm1.setVerticalAlignment(javax.swing.JLabel.CENTER);
        
        JLabel txtm2 = new JLabel();
        txtm2.setText("Machine 2");
        txtm2.setBounds(280, 145, 75, 30);
        txtm2.setVisible(true);
        txtm2.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        txtm2.setVerticalAlignment(javax.swing.JLabel.CENTER);
        add(txtm1);
        add(txtm2);
        int y = 170;
        
        for(int i=0; i<num; i++){
            jname[i] = new JLabel();
            jname[i].setText("Job"+(i+1));
            jname[i].setVisible(true);
            jname[i].setBounds(90, y, 80, 30);
            jname[i].setHorizontalAlignment(javax.swing.JLabel.LEFT);
            jname[i].setVerticalAlignment(javax.swing.JLabel.CENTER);
            
            mach1[i] = new JTextField();
            mach1[i].setBounds(190, y, 80, 30);
            mach1[i].setHorizontalAlignment(javax.swing.JTextField.LEFT);
            mach1[i].setVisible(true);
            
            mach2[i] = new JTextField();
            mach2[i].setBounds(280, y, 80, 30);
            mach2[i].setHorizontalAlignment(javax.swing.JTextField.LEFT);
            mach2[i].setVisible(true);
            
            add(jname[i]);
            add(mach1[i]);
            add(mach2[i]);
           
            y = y + 35;
        }
        
        JButton btnSubmit = new JButton();
        btnSubmit.setText("Submit");
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 14));
        y = y + 20;
        btnSubmit.setBounds(250, y, 100, 30);
        btnSubmit.setVisible(true);
        add(btnSubmit);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getArrays();
                goToTwoMachSeq();
            }
        });
        
    }
    
    private void txtjobnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtjobnoPropertyChange

    }//GEN-LAST:event_txtjobnoPropertyChange

    private void txtjobnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjobnoActionPerformed
       
    }//GEN-LAST:event_txtjobnoActionPerformed

    private void btngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoActionPerformed
        setnojobs();
    }//GEN-LAST:event_btngoActionPerformed

    private void btngoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngoMousePressed

    private void btngoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btngoMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Twojobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Twojobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Twojobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Twojobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Twojobs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtjobno;
    // End of variables declaration//GEN-END:variables
}
